import type { Block } from './guide';

// Long-form project copy, carried over verbatim from newprero.tevih.com.
export const descriptions: Record<string, Block[]> = {
	'closets-by-liberty': [
		{ type: 'p', text: 'Closet organization is a constant struggle, and a massive market. Yet so many solutions seem to miss the mark for the mass market consumer. A unique opportunity was presented to Liberty; a large retail partner approached and asked us to develop something new and better. I was assigned as the Design Lead for this new category, part of a small group of 2 marketers, one engineer, one graphic designer, and myself. In 2.5 years, we dove deep into where other DIY systems fall short, what consumers really desired, and produced a truly innovative system unlike any other, at an approachable price point. Closets by Liberty received the 2020 Platinum ADEX award for Design Excellence, and was included in Design Journals Best Products of 2020. You can learn more about the system at www.closetsbyliberty.com.' },
		{ type: 'p', text: 'The process for developing this system was multi-faceted, with rounds of design, research, iteration, prototyping, and development. We bought every DIY system out there, and I built them all. We worked with contractors, pro organizers, sales associates, and users to find every need and address them.' },
		{ type: 'p', text: 'Walking through the images here, we begin with general market research, identifying storage systems for closet, kitchen, and laundry being a primary pain point with our market. Some key factors were taken into the first round of high level sketch concepts (Note: sketches shown were generated by multiple designers).' },
		{
			type: 'list',
			items: [
				'There is an inherent distrust among this DIY market for wall mounted installation. Finding studs and hoping for the best is scary, and can lead to lots of holes in walls, a specific concern for renters. It also means the system will essentially be permanent, even if in theory it can be removed and rebuilt elsewhere. Therefore a floor-based system was essential.',
				'Customizability is really important, and not just with first installation. Users want the ability to cater to needs that change over time. Reconfiguration should be doable quickly, with minimal or no tools, and with as few limitations as possible.',
				'Redoing your closet organization is a big project; too big for most to swallow. It is the biggest hurdle to purchasing a new system. Even “simple” systems are multi-day projects, with lengthy complicated instructions, and require lots of tools. Users want something far more simple, with few to no tools, that can be done in an afternoon instead of a weekend. Even shopping for the right configuration is a huge project in itself, since you end up committed to that particular configuration more often than not.',
				'Safety is a huge industry concern, in the wake of IKEA’s dresser recall for products tipping. But most people still don’t install anti-tip measures. They are designed as an afterthought, can be unsightly, and again, require finding studs. Users just don’t bother. This process needs to improve.',
			],
		},
		{ type: 'p', text: 'So the need was established for a floor-based, super customizable system that’s really easy to reconfigure, requires little to no tools, can be assembled in a few hours by even a novice, and ensures a user will install it safely. At a mass market price point. Easy peasy, right?' },
		{ type: 'p', text: 'Round one sketches focused on a few ways to accomplish that end goal, at a high level. The details were not worked out, but we presented panels with a handful of different approaches for how a closet system could in theory tackle these issues.' },
		{ type: 'p', text: 'In the next image, I translated the results of those high level concepts in 4 iterations of the winner from round one. These 4 approaches all met the needs we identified, and were all different iterations of the version selected by our panels. These were both rendered for quantitative online research, and prototyped for qualitative.' },
		{ type: 'p', text: 'Once we had results from that, we were on to working out the system details. I lead a series of brainstorm session to focus on both the structure of the system itself, as well as the components and modular accessories therein. Those led to a refined set of concepts that were sketched out (next image), and proven out in prototypes.' },
		{ type: 'p', text: 'Once I developed the final concepts, I worked with our Engineer and vendor to create a works-like, looks-like prototype. We then presented the concept along with 2 current market leaders in our targeted pricing segment in another qual and quant round of research.' },
		{ type: 'p', text: 'We had a winner, but now needed to finesse the design. I dove into the finer aesthetic details, from the drawer fronts, color and hardware combinations, and design of the frames and support structures. This led to, you guessed it, more research! We needed to resonate with our customer, and heard that voice at every stage.' },
		{ type: 'p', text: 'What resulted was one of a kind. Closets by Liberty is based on a simple set of aluminum extrusions that package minimally, but offer incredible strength and versatility. The frames have no front or back, top or bottom, so they are incredibly easy to assemble. Each frame contains recessed side channels to both conceal the holes for the accessory brackets (gotta look pretty), while also forming a snap in channel to help align parts in assembly, as well as serve as a connection method for future accessories. The anti-tip mechanism is fool proof; it needs to be installed in order to complete assembly, and with the slide and lock system, guarantees you’ll hit a stud and secure your system with minimal effort, and no erroneous drilling. The system takes just a couple hours to install, and only needs a handful of screws to assembly. And the best part, all shelves, drawers, clothing rods, and other accessories attach with a shared drop and lock bracket, so all components can install anywhere along the height of the system, and can be moved around and reconfigured in seconds.' },
		{ type: 'p', text: 'That’s a big story to tell. I know, I wrote it. How do you sell that to customers in-aisle though? We developed a highly visual in-store display that helps customers easily identify what components they are buying and intuitively walks them through the shopping journey. Once again, user research allowed us to get this right.' },
		{ type: 'p', text: 'For the online experience, I developed a series of animations to show how the multitude of innovations work, and just how versatile the system is.' },
		{ type: 'p', text: 'I’m happy to say I’ve installed this in multiple spots in my house, and it absolutely checks the boxes. And the nature of the system allows new accessories to be added all the time. Since initial launch, Liberty has added a shoe storage shelf, extra wide rods and shelves, extra narrow rods, shelves, and drawers (to accommodate an even wider range of spaces), and rods that can attach directly form system to wall. And there’s more to come.' },
	],
	'cabinet-hardware': [
		{ type: 'p', text: 'As part of our annual portfolio refresh for The Home Depot, I sought to combine modern with a touch of eclectic and Art Deco for a refreshing cabinet update.' },
	],
	'bath-storage': [
		{ type: 'p', text: 'Our goal was to develop 2 new lines (wire and plastic) of bath accessories for mass market, big-box retail.' },
		{ type: 'p', text: 'To develop these lines, we examined current market offerings and their online reviews to find holes in this category. We designed a number of concepts that either addressed existing issues or introduced new features, while maintaining competitive pricing in production. We presented these concepts to research panels which yielded our chosen design for the flagship item in each category. Off of those flagships, we broadened the line offering.' },
	],
	'off-the-wall': [
		{ type: 'p', text: 'Entryways, mudrooms, closets, laundry rooms and kids rooms all have a unique and often changing set of needs, with space at a premium. The Off-the-Wall collection brings some calm to the chaos, offering a modular and ever expanding system to organize whatever you can throw at it, with a clean and cohesive design, all while keeping your floor clear.' },
		{ type: 'p', text: 'Accessories include a hookrail; bin with 2 pegs; caddy with chalkboard, shelf, and 2 pegs; pegboard; drying rack; wire basket; and iron rest/ironing board holder/steaming station (aka “Finishing Station”).' },
		{ type: 'p', text: 'The finishing station also can be wall mounted, or mounted over the door with included hooks, and includes a custom designed hanger for steaming garments right from the Finishing Station.' },
	],
	'project-62-hook': [
		{ type: 'p', text: 'As part of our annual home hardware portfolio for our various customers, we were presented with an opportunity to develop concepts for Target’s trendy Project 62 house brand. A relatively quick turnaround, this hook maintained the original design intent for an eclectic, unique, and functional end result.' },
	],
	'durabilt': [
		{ type: 'p', text: 'Home Products International is the 800 lb. gorilla of ironing boards. If you live in North America and own an ironing board, HPI probably made it. To keep ahead of the pack, we pinpointed the biggest concern of those who iron: board stability.' },
		{ type: 'p', text: 'When closed, the Durabilt Board has the same packaging footprint as any other board (a must to fit into retail and shipping environments cost effectively), but when opened, the front legs spread up to 16″ wider, increasing stability by up to 40%. It features non-slip and self-leveling feet, a soft touch release lever, an easy carry handle, and an iron rest that enables you to set your iron down in multiple ways. This is not your mother’s ironing board.' },
	],
	'dryer-sheet': [
		{ type: 'p', text: 'Dryer sheets have a way of getting lost. The box falls somewhere behind the machine. Individual sheets find new homes in pant legs. In an effort to wrangle those misbehaving sheets, I developed 2 products for HPI.' },
		{ type: 'p', text: 'The Dryer Sheet Dispenser is a koozie for your box of Bounce. With a soft touch opening to keep the scent in while allowing easy access, and 4 strong magnets on the base, this box will hold your standard sized box of dryer sheets to any surface of your dryer.' },
		{ type: 'p', text: 'The Sheet Keeper is a dryer ball that helps pummel and soften your clothes, with a center pucker to keep hold of your dryer sheets. No more dryer sheets embarrassingly falling out of your pant leg at work.' },
	],
	'theta': [
		{ type: 'p', text: 'Working with Cephius LLC, I brought what was a shape and basic concept cobbled from cardboard and electrical tape into a sleek, elegant, multi-purpose and manufacturable solution to an irritating fact of life. THETA is a truly modern response to unruly ear buds, and serves a dual purpose as a beautiful smartphone stand.' },
		{ type: 'p', text: 'THETA is not only functional and versatile, but it is uniquely designed to live in the same aesthetic world as the devices for which it is made. I worked with Cephius throughout the entire design and manufacturing process to ensure the masses could enjoy their headphones a few moments faster. Visitwww.buytheta.com and see how life is better untangled.' },
	],
	'the-loop': [
		{ type: 'p', text: 'When Loft 312 approached me with their new idea for poop bag dispensing, they had little more than an engineered concept. Our goal was to turn a novel dispensing concept into a production-ready, sleek, innovative, and desireable dog accessory.' },
		{ type: 'p', text: 'The Loop is a well-functioning, minimal bag holder that doesn’t try to look like something it’s not, like a bone or fire hydrant. The design and aesthetic only adds to the function. It’s got a great big loop for grip and all sorts of toting possibilities, and a unique grab and rip function for easy single bag dispensing. A perfect addition for any leash (or diaper bag). Hit up www.loft312.com for more info.' },
	],
	'tricorbraun': [
		{ type: 'p', text: 'At TricorBraun, I lead and collaborated on custom bottle and packaging design projects for TB’s range of international clients. Process included initial sketch ideation, detailed Solidworks modeling, FDM and Objet prototyping, customer presentations, vendor relations and followup, and quality control throughout the sampling, unit cavity, and full cavity production processes. While at TB, I successfully launched over 20 custom packaging designs into production, have been awarded 7 patents, and have more pending.' },
	],
	'menorahs': [
		{ type: 'p', text: 'Being the lone Jewish designer at tag, the job of designing new and innovative menorahs for the seasonal line and private label clients fell on me.' },
	],
	'swingline': [
		{ type: 'p', text: 'While at ACCO Brands in their Swingline division, I was afforded the opportunity to collaborate with great designers every day. Even though it was early in my career, I was able to meaningfully contribute to the product line over the course of my year-long internship. And yes, Office Space references and jokes were abundant.' },
	],
	'home-decor': [
		{ type: 'p', text: 'While at tag, I worked to create a new line somewhat outside their typical whimsical wheelhouse to be used mainly for existing and new private label customers. The look was sleek and understated, and always with a practical twist. Yeah, I’m like that.' },
	],
	'bamboocell': [
		{ type: 'p', text: 'My undergraduate thesis, Bamboocell focuses on the way we interact with office tools in a home office. A home office is a sanctuary, and the tools one uses therein should cater to that. This office suite includes a wireless USB hub, ambient lamp, and tape dispenser, and is designed to be made in sustainable materials, such as bamboo, and Tenite, a cellulosic that can be imbued with scent for a truly custom experience.' },
	],
	'wayfinders': [
		{ type: 'p', text: 'Our Senior Design show was to be held in the very confusing UIC Art + Architecture Building. In order to help direct people to their locations of interest, I and 2 colleagues developed a color-coded arrow placard system. The arrows were labeled with initials of the 3 departments exhibiting at the show. The nesting arrows would group together at the entrance and separate when neccessary to point guests in the right direction. Color indicators were placed in the final exhibition spaces to match the color scheme on each placard. After the show, School Director Marcia Lausen asked that we make this a permanent fixture.' },
	],
	'tfg-rebrand': [
		{ type: 'p', text: 'While at tag, I was part of a small team charged with rejuvenating their furniture brand, TFG. Besides product design, I created a new graphic presence that better fit the TFG style while staying true to the greater tag brand. Total print pieces consisted of 8.5×11 catalogue, 11×17 concept presentation book, and letterhead. More can be seen at www.tagltd.com.' },
	],
	'otto-bench': [
		{ type: 'p', text: 'Fitness equipment is not designed for small urban spaces. This is the problem Life Fitness asked us to solve. The Otto-Bench combines a multi-adjustable bench, olympic bench press, and free weights into a sleek, stylish, and perhaps most importantly, inconspicuous long ottoman. My design solution was the winner of this competition, and has since been featured in Home Gym Magazine, Shape Magazine Germany, popularscience.com, and Gizmodo.com, among others.' },
	],
};

/** Live product sites, where the project has one. */
export const projectSites: Record<string, string> = {
	'closets-by-liberty': 'http://www.closetsbyliberty.com',
	'the-loop': 'http://www.loft312.com/',
	'theta': 'http://www.buytheta.com/',
};
